# Generated by Django 5.1.1 on 2024-09-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carvilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardescription',
            name='horsepower',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardescription',
            name='miles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardescription',
            name='model',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
