# Generated by Django 5.1.1 on 2024-09-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carvilla', '0002_cardescription_horsepower_cardescription_miles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardescription',
            old_name='miles',
            new_name='kmph',
        ),
    ]
